name: Beehome GitHub Actions
on: 
  workflow_dispatch:
  pull_request:
      branches:
          - main
jobs:
  BeeHome-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
     
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt
          pip install -r ci_requirments.txt
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
     
      - name: Test with pytest
        run: |
          pytest
          
      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v1.8
        
      - run: echo "🍏 This job's status is ${{ job.status }}."
