name: BeeHomeCreateReelaseCandidate
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  BeeHomeCreateReelaseCandidateActions:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "Getting version"
      - uses: actions/checkout@master
        with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - run: echo "Branch creation"
      - name: Create Branch      
        run: |
            RELEASE_BRANCH_NAME=$(python ./.github/Versions/VersionUpdateScript.py get_release_branch_name)
            git branch $RELEASE_BRANCH_NAME
      
      - run: echo "Update Version And Creat Local Tag"
      - name: UpdateVersionAndCreateLocalTag
        run: |
            python ./.github/Versions/VersionUpdateScript.py inc-minor
            VERSION=$(python ./.github/Versions/VersionUpdateScript.py get_version)
            git tag -a $VERSION  -m "latest version"
