name: BeehomePullRequestJobs
on: [pull_request]
jobs:
  BeeHomePullRequestGitHubActions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - run: echo "Enforcing name"
      
      - uses: haya14busa/action-cond@v1
        id: regex_rule
        with:
          cond: ${{ github.base_ref=='main'}}
          if_true: '[^(Feature|Fix|Infrastructure|Release|Merge)]\s*\[v[0-9]+.[0-9]+\]\s*MW-[0-9]+'
          if_false: '[^(Feature|Fix)]\s*'
      - name: Use conditional value
        run: |
            echo "${{ github.base_ref }}"
            echo "${{ steps.regex_rule.outputs.value }}"
      - uses: deepakputhraya/action-pr-title@master
        with:
         regex: ${{ steps.regex_rule.outputs.value }}
         github_token: ${{ github.token }} # Default: ${{ github.token }}
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@master
        with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt
          pip install -r ci_requirments.txt
          
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
     
      - name: Install plugin
        run: pip install pytest-github-actions-annotate-failures

      - name: Test with pytest
        run: |
          pytest
             
      - run: echo "🍏 This job's status is ${{ job.status }}."
