name: BeehomePullRequestJobs
on: 
  workflow_dispatch:
  pull_request:
      branches:
          - main
          - release/**
permissions: write-all

jobs:
  BeeHomePullRequestGitHubActions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - run: echo "Enforcing name"
      - uses: deepakputhraya/action-pr-title@master
        with:
         regex: '[^(Feature|Fix|Fnfrastructure|Release|Merge)]\s*\[v[0-9]+.[0-9]+\]\s*MW-[0-9]+' # Regex the title should match.
         github_token: ${{ secrets.MY_TOKEN }} # Default: ${{ github.token }}
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@master
        with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt
          pip install -r ci_requirments.txt
          
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
     
      - name: Install plugin
        run: pip install pytest-github-actions-annotate-failures

      - name: Test with pytest
        run: |
          pytest
             
      - run: echo "🍏 This job's status is ${{ job.status }}."
